Hw 2
AndreyVolokhatyy/AndreyVolokhatyy_LivelUp pull request #1
Opened 2021-08-30 16:34 UTC by AndreyVolokhatyy

Домашнее задание номер 2

2021-09-06 19:55 UTC, khda91 requested changes
Обнови, плиз, java на 11 версю и добавь checkstyle

2021-09-06 19:55 UTC, khda91 commented on pom.xml
> +        <maven.compiler.target>1.8</maven.compiler.target>
А почему Java 8?

2021-09-15 10:41 UTC, AndreyVolokhatyy commented on pom.xml
> +        <maven.compiler.target>1.8</maven.compiler.target>
<maven.compiler.source>11</maven.compiler.source>
 <maven.compiler.target>11</maven.compiler.target>
 
 commit 01aed88deedd875159b05bcafdf36183172ee311

2021-09-18 09:43 UTC, khda91 approved these changes
Работа принята

2021-09-18 09:43 UTC, merged